-- ============================================================
-- 035: Creator DYI Instagram data-export import
--
-- A no-Meta, no-OAuth way for a creator to hand us their own reach + posting
-- history: they download their Instagram data ("Settings → Accounts Center →
-- Your information and permissions → Download your information", JSON format),
-- upload the ZIP, and we parse it server-side. This gives us the numbers that
-- the login-free public fetch can't always see (exact follower/following counts,
-- full post history + posting cadence) — sourced from the creator themselves.
--
--   data_export_imported_at — when we last parsed an upload
--   data_export_summary     — { followers, following, posts, posts_last_30d,
--                               posts_last_90d, avg_gap_days, first_post_at,
--                               last_post_at, username, imported_at }
--
-- This is a self-sourced signal: stronger than typed-in numbers (the export is
-- generated by Instagram), but softer than a live OAuth/public read, so it sits
-- alongside the 'public' rung rather than replacing an active OAuth connection.
-- ============================================================

ALTER TABLE creators
  ADD COLUMN IF NOT EXISTS data_export_imported_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS data_export_summary JSONB;
